// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXt5okth3knIHYy8qibRfvxHZsrbZrlZ8',
    appId: '1:967208725848:web:22e3e746e91402b0abc92d',
    messagingSenderId: '967208725848',
    projectId: 'kid-parent-app-65a80',
    authDomain: 'kid-parent-app-65a80.firebaseapp.com',
    databaseURL:
        'https://kid-parent-app-65a80-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'kid-parent-app-65a80.firebasestorage.app',
    measurementId: 'G-YJTSKQDRRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjGYMvsCZVni2wt8ZUUNuovZwFCPamUo',
    appId: '1:967208725848:android:4fada741fc840941abc92d',
    messagingSenderId: '967208725848',
    projectId: 'kid-parent-app-65a80',
    databaseURL:
        'https://kid-parent-app-65a80-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'kid-parent-app-65a80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4xh6IWnNc7gZSlBrcRHSLsv9ff9K8lM',
    appId: '1:967208725848:ios:4172e487aa187f55abc92d',
    messagingSenderId: '967208725848',
    projectId: 'kid-parent-app-65a80',
    databaseURL:
        'https://kid-parent-app-65a80-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'kid-parent-app-65a80.firebasestorage.app',
    iosBundleId: 'com.example.kidsecureParentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4xh6IWnNc7gZSlBrcRHSLsv9ff9K8lM',
    appId: '1:967208725848:ios:4172e487aa187f55abc92d',
    messagingSenderId: '967208725848',
    projectId: 'kid-parent-app-65a80',
    databaseURL:
        'https://kid-parent-app-65a80-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'kid-parent-app-65a80.firebasestorage.app',
    iosBundleId: 'com.example.kidsecureParentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXt5okth3knIHYy8qibRfvxHZsrbZrlZ8',
    appId: '1:967208725848:web:41e17454316f1d6dabc92d',
    messagingSenderId: '967208725848',
    projectId: 'kid-parent-app-65a80',
    authDomain: 'kid-parent-app-65a80.firebaseapp.com',
    databaseURL:
        'https://kid-parent-app-65a80-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'kid-parent-app-65a80.firebasestorage.app',
    measurementId: 'G-KNQGYT40T0',
  );
}
